server:
  port: 8084

spring:
  application:
    name: kualit-marvel-s3-worker
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      sqs:
        enabled: true
        endpoint: http://localhost:4566
      s3:
        enabled: true
        endpoint: http://s3.localhost.localstack.cloud:4566/
sqs:
  queue-name: character-picture-queue
s3:
  bucket-name: marvel-characters-pictures




